name: Scala

on:
  pull_request: {}
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        java:
          - jdk16

    steps:
      - uses: actions/checkout@v2.3.2

      - name: "Starting up Pulsar 🐳"
        run: ./run.sh

      - name: "Cache for sbt & coursier ♨️"
        uses: coursier/cache-action@v4.1

      - name: "Install Nix ❄️"
        uses: cachix/install-nix-action@v12

      - name: "Run with ${{ matrix.java }} 🚀"
        # Setting SBT_OPTS because of this bug: https://github.com/sbt/sbt-site/issues/169
        run: nix-shell \
               --argstr java "${{ matrix.java }}" \
               --run "SBT_OPTS='--illegal-access=permit' sbt + 'IntegrationTest/test;test;makeSite;doc'"

      - name: "Shutting down Pulsar 🐳"
        run: docker-compose down
