name: Microsite

on:
  push:
    branches:
      - master
    #paths:
      #- 'docs/**'
    #tags:
      #- v[0-9]+.[0-9]+.[0-9]+

jobs:
  publish:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.2
        with:
          fetch-depth: 0 # fetch all branches & tags

      - name: "Install Nix ❄️"
        uses: cachix/install-nix-action@v12

      - name: "Install SSH 🔑 for GH pages"
        uses: shimataro/ssh-key-action@v2.3.1
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - run: git config --global user.email "neutron-site-bot@profunktor.dev"
      - run: git config --global user.name "neutron-site-bot"

        # Setting SBT_OPTS because of this bug: https://github.com/sbt/sbt-site/issues/169
      - name: "Build microsite 🚧"
        run: nix-shell --run "SBT_OPTS='--illegal-access=permit' sbt ghpagesPushSite"
